[INFO   ] Logger: Record log in /storage/emulated/0/asistente_predicacion_migracion_kivy/.kivy/logs/kivy_25-05-27_99.txt
[INFO   ] Kivy: v2.3.1
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.13.2 (main, Apr 27 2025, 04:34:27) [GCC 11.4.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[INFO   ] Logger: Purge log fired. Processing...
[INFO   ] Logger: Purge finished!
[INFO   ] Factory: 195 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.2 v1.r38p1-01eac0-mbs2v41_0.1576f2b73e48a66e09aaf3834ddc664d'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-G68'>
[INFO   ] GL: OpenGL parsed version: 3, 2
[INFO   ] GL: Texture max size <16383>
[INFO   ] GL: Texture max units <64>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "kivy/_event.pyx", line 235, in kivy._event.EventDispatcher.__init__
[WARNING] stderr: TypeError: object.__init__() takes exactly one argument (the instance to initialize)
[WARNING] stderr: 
[WARNING] stderr: The above exception was the direct cause of the following exception:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/asistente_predicacion_migracion_kivy/main.py", line 65, in <module>
[WARNING] stderr:     AsistentePredicacionApp().run()
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/app.py", line 955, in run
[WARNING] stderr:     self._run_prepare()
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/app.py", line 925, in _run_prepare
[WARNING] stderr:     root = self.build()
[WARNING] stderr:   File "/storage/emulated/0/asistente_predicacion_migracion_kivy/main.py", line 37, in build
[WARNING] stderr:     self.sm.add_widget(PantallaTemasProfundos(name='temas_profundos', volver_callback=self.volver_al_menu, idioma=self.idioma))
[WARNING] stderr:                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[WARNING] stderr:   File "/storage/emulated/0/asistente_predicacion_migracion_kivy/pantallas/temas_profundos.py", line 19, in __init__
[WARNING] stderr:     super().__init__(**kwargs)
[WARNING] stderr:     ~~~~~~~~~~~~~~~~^^^^^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/uix/relativelayout.py", line 274, in __init__
[WARNING] stderr:     super(RelativeLayout, self).__init__(**kw)
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
[WARNING] stderr:     super(FloatLayout, self).__init__(**kwargs)
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/uix/layout.py", line 76, in __init__
[WARNING] stderr:     super(Layout, self).__init__(**kwargs)
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/uix/widget.py", line 357, in __init__
[WARNING] stderr:     super(Widget, self).__init__(**kwargs)
[WARNING] stderr:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
[WARNING] stderr:   File "kivy/_event.pyx", line 238, in kivy._event.EventDispatcher.__init__
[WARNING] stderr: TypeError: Properties ['idioma'] passed to __init__ may not be existing property names. Valid properties are ['center', 'center_x', 'center_y', 'children', 'cls', 'disabled', 'height', 'ids', 'manager', 'motion_filter', 'name', 'opacity', 'parent', 'pos', 'pos_hint', 'right', 'size', 'size_hint', 'size_hint_max', 'size_hint_max_x', 'size_hint_max_y', 'size_hint_min', 'size_hint_min_x', 'size_hint_min_y', 'size_hint_x', 'size_hint_y', 'top', 'transition_progress', 'transition_state', 'width', 'x', 'y']
