[INFO   ] Logger: Record log in /storage/emulated/0/asistente_predicacion_migracion_kivy/.kivy/logs/kivy_25-05-27_38.txt
[INFO   ] Kivy: v2.3.1
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.13/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.13.2 (main, Apr 27 2025, 04:34:27) [GCC 11.4.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[INFO   ] Logger: Purge log fired. Processing...
[INFO   ] Logger: Purge finished!
[INFO   ] Factory: 195 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/asistente_predicacion_migracion_kivy/main.py", line 9, in <module>
[WARNING] stderr:     from pantallas.login import PantallaLogin
[WARNING] stderr:   File "/storage/emulated/0/asistente_predicacion_migracion_kivy/pantallas/login.py", line 11, in <module>
[WARNING] stderr:     from traducciones import traducir, idioma_actual
[WARNING] stderr: ImportError: cannot import name 'idioma_actual' from 'traducciones' (/storage/emulated/0/asistente_predicacion_migracion_kivy/traducciones.py)
